name: Deploy to Firebase Hosting with Node.js server on PR
on: pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Install dependencies and build the project
      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build

      # Start the Node.js server in the background
      - name: Start Node.js Server
        run: node server/index.js &
        
      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BALL_WEBSITE_72C4A }}'
          projectId: ball-website-72c4a
